import { PDFDocument, StandardFonts, rgb, PageSizes } from 'pdf-lib';
import type { ScanResult } from '@/types/scan';
import { groupByCategory } from '@/lib/scanner/categories';

const SEVERITY_COLOR: Record<string, [number, number, number]> = {
  critical: [0.8, 0.15, 0.15],
  high: [0.85, 0.4, 0.1],
  medium: [0.85, 0.65, 0.1],
  low: [0.3, 0.5, 0.85],
  info: [0.5, 0.5, 0.5],
  pass: [0.15, 0.6, 0.3],
};

/** Renders a branded, print-styled PDF of the full report (no external service needed). */
export async function renderReportPdf(result: ScanResult, appName = 'Aegis'): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage(PageSizes.A4);
  const { width, height } = page.getSize();
  const margin = 50;
  let y = height - margin;

  const drawText = (text: string, opts: { size?: number; f?: typeof font; color?: [number, number, number] } = {}) => {
    const size = opts.size ?? 11;
    if (y < margin + size) {
      page = pdf.addPage(PageSizes.A4);
      y = height - margin;
    }
    page.drawText(text, {
      x: margin,
      y,
      size,
      font: opts.f ?? font,
      color: rgb(...(opts.color ?? [0.1, 0.1, 0.1])),
    });
    y -= size + 8;
  };

  drawText(appName, { size: 22, f: bold, color: [0.1, 0.2, 0.6] });
  drawText('Website Security Scan Report', { size: 14, f: bold });
  y -= 4;
  drawText(`Target: ${result.hostname}`, { size: 11 });
  drawText(`Scanned: ${new Date(result.scannedAt).toLocaleString()}`, { size: 11 });
  drawText(`Score: ${result.score} / 100  (Grade ${result.grade})`, {
    size: 16,
    f: bold,
    color: result.score >= 70 ? [0.15, 0.6, 0.3] : result.score >= 40 ? [0.85, 0.65, 0.1] : [0.8, 0.15, 0.15],
  });
  y -= 10;

  drawText('Findings', { size: 14, f: bold });
  y -= 2;

  const severityRank: Record<string, number> = { critical: 5, high: 4, medium: 3, low: 2, info: 1, pass: 0 };

  for (const group of groupByCategory(result.findings)) {
    y -= 4;
    drawText(group.label, { size: 12, f: bold, color: [0.15, 0.2, 0.35] });

    const ordered = [...group.findings].sort((a, b) => (severityRank[b.severity] ?? 0) - (severityRank[a.severity] ?? 0));

    for (const finding of ordered) {
      const color = SEVERITY_COLOR[finding.severity] ?? [0.1, 0.1, 0.1];
      drawText(`[${finding.severity.toUpperCase()}] ${finding.title}`, { size: 12, f: bold, color });
      for (const line of wrapLines(finding.detail, 95)) {
        drawText(line, { size: 10 });
      }
      if (!finding.passed) {
        const recLines = wrapLines(finding.recommendation, 90);
        recLines.forEach((line, i) => {
          drawText(i === 0 ? `Recommendation: ${line}` : line, { size: 10, color: [0.3, 0.3, 0.3] });
        });
      }
      y -= 6;
    }
  }

  y -= 10;
  drawText('Generated by ' + appName + ' — automated scan, not a substitute for a full manual audit.', {
    size: 9,
    color: [0.5, 0.5, 0.5],
  });

  return pdf.save();
}

/** Simple greedy word-wrap by character count (pdf-lib doesn't measure or
 * wrap text for us, and this app doesn't pull in a layout engine for one
 * report). Splits on whitespace only — a single "word" longer than
 * maxChars is left on its own line rather than hard-broken mid-word, which
 * is an acceptable tradeoff for report prose (URLs, mainly) vs. the
 * complexity of grapheme-aware breaking. */
function wrapLines(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [''];
}
